### ISSUE TITLE
micronaut-jms-aws-sqs fails to build for Maven

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-guides#1184]
When attempting to build `micronaut-jms-aws-sqs`, the gradle build passes, but the maven build fails with:

```
ERROR] COMPILATION ERROR : G [8s]
[ERROR] /.../micronaut-guides/build/code/micronaut-jms-aws-sqs/micronaut-jms-aws-sqs-maven-java/src/main/java/example/micronaut/SqsClientFactory.java:[3,29] package com.amazonaws.regions does not exist
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project micronautguide: Compilation failure
[ERROR] /.../micronaut-guides/build/code/micronaut-jms-aws-sqs/micronaut-jms-aws-sqs-maven-java/src/main/java/example/micronaut/SqsClientFactory.java:[3,29] package com.amazonaws.regions does not exist
[ERROR]
[ERROR] -> [Help 1]
```

Looking into it, it seems like adding

```
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-core</artifactId>
      <scope>test</scope>
    </dependency>
```

to the POM stops it being used as a transitive dependency of `io.micronaut.jms:micronaut-jms-sqs:2.1.0` for compilation

If I remove the above dependency, the guide builds and the tests pass

For now, I am [disabling maven for `micronaut-jms-aws-sqs`](https://github.com/micronaut-projects/micronaut-guides/pull/1185)

**Comment by alvarosanchez** [comment]
So is this not what we discussed [here](https://github.com/micronaut-projects/micronaut-guides/pull/1160#discussion_r1029237675)?

Seems like it was broken by #1157, the guides feature might be different than the starter one

**Comment by timyates** [comment]
@sdelamo @alvarosanchez Ahhh, so in https://github.com/micronaut-projects/micronaut-guides/pull/1160/files#diff-49973c2c2d2dadb5314107490012f0b84f395667c3a4fa1d4bb5852304063780 for the guide, we changed sdk-core from test to an implementation dependency. But this was not copied over to the localstack feature in starter

https://github.com/micronaut-projects/micronaut-starter/blob/62f0a8d51bdcad86df43bfffddd0ea6cba45f60d/starter-core/src/main/java/io/micronaut/starter/feature/test/LocalStack.java#L90-L93

I can think of 2 options here:

1. Remove test() in starter
2. Add a new feature in guides that extends Localstack, and overrides "apply" to add the sdk-core dependency to the implementation ones

Localstack is pulled in as a "invisibleFeature", so I'd be inclined to do it in guides 🤔

**Comment by sdelamo** [comment]
so, micronaut-jms-sqs has a transitive dependency to `aws-java-sdk-core`. And because `micronaut-jms-sqs` is in the main classpath,  `aws-java-sdk-core` is in the main classpath as well. 

local stack feature adds `aws-java-sdk-core` to the test classpath and because of that maven does not bring it to the main classpath. 

And this only manifest with Maven. Not with gradle. is that correct?

**Comment by timyates** [comment]
Yes, as far as I can tell...  Adding as a test dependency for Maven seems to remove the transitive dependency from the implementation 🤔

**Comment by sdelamo** [comment]
I think the correct solution would be to modify the localstack starter feature. For maven, if micronaut-jms-sqs dependency is present it should not add the dependency `aws-java-sdk-core`.

https://github.com/micronaut-projects/micronaut-starter/blob/62f0a8d51bdcad86df43bfffddd0ea6cba45f60d/starter-core/src/main/java/io/micronaut/starter/feature/test/LocalStack.java#L90-L93

thoughts?

**Comment by timyates** [comment]
@sdelamo So it works in both Gradle and Maven if we just remove the `aws-java-sdk-core` dependency, as it comes in transitively for both.  Maybe the solution is simply to remove it from Localstack for 3.8.1?

**Comment by timyates** [comment]
https://github.com/micronaut-projects/micronaut-starter/pull/1580

**Comment by alvarosanchez** [comment]
Checking the dependency tree shows this:

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ micronautguide ---
[INFO] example.micronaut:micronautguide:jar:0.1
[INFO] +- io.micronaut.jms:micronaut-jms-sqs:jar:2.1.0:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-sqs:jar:1.12.372:compile
[INFO] |  |  \- (com.amazonaws:aws-java-sdk-core:jar:1.12.372:compile - omitted for duplicate)
[INFO] |  \- io.micronaut.aws:micronaut-aws-sdk-v1:jar:3.10.4:compile (version managed from 3.7.1)
[INFO] |     \- (com.amazonaws:aws-java-sdk-core:jar:1.12.372:compile - omitted for duplicate)
[INFO] \- com.amazonaws:aws-java-sdk-core:jar:1.12.372:test (scope not updated to compile)
```

Which confirms that only the test dependency is selected.

https://github.com/micronaut-projects/micronaut-starter/pull/1580 looks like the correct option to me.

**Comment by sdelamo** [comment]
Closed via https://github.com/micronaut-projects/micronaut-starter/pull/1580
